//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWork {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class L10N {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L10N() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectWork.L10N", typeof(L10N).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string activeStatus {
            get {
                return ResourceManager.GetString("activeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All projects.
        /// </summary>
        public static string allProjects {
            get {
                return ResourceManager.GetString("allProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string completedStatus {
            get {
                return ResourceManager.GetString("completedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection problem.
        /// </summary>
        public static string connectionProblem {
            get {
                return ResourceManager.GetString("connectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Producteev.
        /// </summary>
        public static string connecttoproducteev {
            get {
                return ResourceManager.GetString("connecttoproducteev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/Add Task.
        /// </summary>
        public static string editaddTask {
            get {
                return ResourceManager.GetString("editaddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string fivePriority {
            get {
                return ResourceManager.GetString("fivePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string fourPriority {
            get {
                return ResourceManager.GetString("fourPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labels.
        /// </summary>
        public static string labelsTitle {
            get {
                return ResourceManager.GetString("labelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to networks.
        /// </summary>
        public static string networksTitle {
            get {
                return ResourceManager.GetString("networksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Low.
        /// </summary>
        public static string onePriority {
            get {
                return ResourceManager.GetString("onePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string projectsTitle {
            get {
                return ResourceManager.GetString("projectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by priority.
        /// </summary>
        public static string sortbypriority {
            get {
                return ResourceManager.GetString("sortbypriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by title.
        /// </summary>
        public static string sortbytitle {
            get {
                return ResourceManager.GetString("sortbytitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string tasksTitle {
            get {
                return ResourceManager.GetString("tasksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string threePriority {
            get {
                return ResourceManager.GetString("threePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string twoPriority {
            get {
                return ResourceManager.GetString("twoPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string zeroPriority {
            get {
                return ResourceManager.GetString("zeroPriority", resourceCulture);
            }
        }
    }
}
