package me.trapridge.chordz;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class ChordData {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;	
	@DatabaseField
	String name;
	@DatabaseField
	int sixth;
	@DatabaseField
	int fifth;
	@DatabaseField
	int fourth;
	@DatabaseField
	int third;
	@DatabaseField
	int second;
	@DatabaseField
	int first;
	
	ChordData() {
		// needed by ormlite
	}

	public ChordData(String name, 
			int sixth, 
			int fifth, 
			int fourth, 
			int third, 
			int second, 
			int first) {
		this.name = name;
		this.sixth = sixth;
		this.fifth = fifth;
		this.fourth = fourth;
		this.third = third;
		this.second = second;
		this.first = first;
	}

	@Override
	public String toString() {
		return this.name;
		/*
		StringBuilder sb = new StringBuilder();
		sb.append("name: " + name + "\n");
		sb.append("positions: " + sixth + ", "
				+ fifth + ", " 
				+ fourth + ", " 
				+ third + ", " 
				+ second + ", " 
				+ first + "\n");
		return sb.toString();*/
	}
}